# --- Upstreams ---
upstream api-v1 {
    server api-v1-1:8000;
    server api-v1-2:8000;
    server api-v1-3:8000;
}

upstream api-v2 {
    server api-v2:8000;
}

# --- Route A/B : traduit le header en nom d'upstream ---
map $http_x_experiment_group $upstream_choice {
    default   api-v1;
    debug     api-v2;
}

# --- Rate limiting : zone mémoire pour tracker les IP ---
limit_req_zone $binary_remote_addr zone=predict_limit:10m rate=10r/s;

# --- Redirection HTTP -> HTTPS ---
server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}

# --- Serveur principal HTTPS ---
server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/certs/nginx.crt;
    ssl_certificate_key /etc/nginx/certs/nginx.key;

    location /predict {
        auth_basic           "Zone restreinte";
        auth_basic_user_file /etc/nginx/.htpasswd;

        limit_req zone=predict_limit burst=5 nodelay;

        proxy_pass http://$upstream_choice;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# --- Monitoring interne (non exposé publiquement) ---
server {
    listen 8080;
    server_name localhost;

    location /nginx_status {
        stub_status;
    }
}